/**
 * The clip viewer.
 *
 * A five-second clip costs minutes of a shared 16 GB card, so it is treated as
 * something to be studied: it never autoplays, it never loses your place, and
 * every number it prints can be trusted or is marked as approximate.
 *
 * Shape, per the build specification §9.1 — all chrome sits BELOW the frame as
 * a ruled caption block, never as a translucent overlay:
 *
 *     ┌──────────────┐
 *     │    video     │
 *     ├──────────────┤  1 px grey rule
 *     │  scrub rail  │
 *     │ frame ticks  │
 *     │  transport   │
 *     ├──────────────┤  1 px grey rule
 *     │   caption    │
 *     └──────────────┘
 *
 * Frame accuracy: seeks go to the midpoint of the target frame and the landed
 * frame is read back — from `requestVideoFrameCallback().mediaTime` where the
 * browser has it, from `currentTime` where it does not. A seek that misses is
 * nudged once; a second miss puts the player into relative stepping and prints
 * a dagger against the counter. It degrades to honest rather than to wrong.
 */

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
} from 'react'
import { fileUrl, type FileRef } from '../../lib/comfy'
import type { HistoryEntry } from '../../lib/history'
import { adoptSource, settings, type DeskId } from '../../lib/session'
import {
  Readout,
  britishDateTime,
  clamp,
  clock,
  dimensions,
  extension,
  frameAt,
  frameCount,
  humanDuration,
  padFrame,
  stem,
  timeOfFrame,
} from './Readout'
import { FrameTicks } from './FrameTicks'
import { ScrubRail } from './ScrubRail'
import { Divider, Hairline, IconButton, LinkAction, RING, TextButton } from './TransportButtons'

/**
 * Whether this browser will tell us which frame it is showing. Firefox will
 * not, and the counter says so rather than guessing.
 */
const HAS_RVFC =
  typeof HTMLVideoElement !== 'undefined' &&
  typeof HTMLVideoElement.prototype.requestVideoFrameCallback === 'function'

const SPEEDS: number[] = [0.25, 0.5, 1, 2]
const SPEED_LABEL: Record<string, string> = { '0.25': '¼', '0.5': '½', '1': '1×', '2': '2×' }

/** What the player hands over when a frame is sent to a desk. */
export type UseFrameRequest = {
  desk: DeskId
  /** Frame index inside the clip. */
  frame: number
  /** Its time in seconds — the midpoint of the frame. */
  time: number
  /** The frame as a PNG at the clip's native resolution. */
  blob: Blob
  /** The same bytes named ready for `uploadImage()`. */
  file: File
  /** The record the clip came from, when it came from one. */
  entry: HistoryEntry | null
  /** The clip itself, for lineage. */
  clip: FileRef | null
}

export type PlayerKeyboard = 'scoped' | 'global' | 'off'

export type PlayerProps = {
  /** The clip, as ComfyUI holds it. Ignored when `src` is given. */
  file?: FileRef | null
  /** A ready-made URL, for a clip that is not a ComfyUI output. */
  src?: string | null
  /** The archive record: supplies the frame rate, the frame count and the byline. */
  entry?: HistoryEntry | null
  /** Frames per second. From the record, never probed. */
  fps?: number | null
  /** Total frames, when known ahead of metadata. */
  frames?: number | null
  /** A cached poster, so the frame is not black while the clip loads. */
  poster?: string | null
  /** Replaces the generated specification line. */
  caption?: ReactNode
  /** Replaces the generated byline. */
  byline?: ReactNode
  /**
   * `scoped` (default) listens only while focus is inside the player or it is
   * full screen; `global` listens everywhere; `off` never listens. Every
   * binding is dead while a text field has focus, in all three.
   */
  keyboard?: PlayerKeyboard
  /** Take focus on mount — for the detail overlay, not for the desk. */
  autoFocus?: boolean
  className?: string
  /** Receives a frame lifted out of the clip. Falls back to `adoptSource`. */
  onUseFrame?: (request: UseFrameRequest) => void
  /** Mirrors anything the player says, for a shell that keeps one notice area. */
  onNotice?: (text: string) => void
}

type Notice = { kind: 'info' | 'error'; text: string }

function saveBlob(blob: Blob, name: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = name
  a.rel = 'noopener'
  document.body.appendChild(a)
  a.click()
  a.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 10_000)
}

function isTypingTarget(target: EventTarget | null): boolean {
  const el = target as HTMLElement | null
  return !!el && (el.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName))
}

/**
 * The viewer. Keyed on the clip so that opening a different one starts from a
 * clean slate — no stale duration, no stale frame, no leftover A–B range —
 * without a reset effect firing a second render on every change.
 */
export function Player(props: PlayerProps) {
  const clip = props.file ?? props.entry?.file ?? null
  const src = props.src ?? (clip ? fileUrl(clip) : null)
  return <PlayerBody key={src ?? 'no-clip'} {...props} />
}

function PlayerBody({
  file = null,
  src: srcProp = null,
  entry = null,
  fps: fpsProp = null,
  frames: framesProp = null,
  poster = null,
  caption,
  byline,
  keyboard = 'scoped',
  autoFocus = false,
  className = '',
  onUseFrame,
  onNotice,
}: PlayerProps) {
  const clip: FileRef | null = file ?? entry?.file ?? null
  const src = srcProp ?? (clip ? fileUrl(clip) : null)

  const prefs = useSyncExternalStore(settings.subscribe, settings.get)
  const loop = prefs.loop
  const speed = SPEEDS.includes(prefs.speed) ? prefs.speed : 1

  const fps = fpsProp ?? entry?.fps ?? null
  /** What the arithmetic uses. Never shown as fact when `fps` is null. */
  const effFps = fps && fps > 0 ? fps : 24

  const rootRef = useRef<HTMLElement | null>(null)
  const videoRef = useRef<HTMLVideoElement | null>(null)
  const menuRef = useRef<HTMLDivElement | null>(null)
  const menuPanel = useRef<HTMLDivElement | null>(null)
  const menuTrigger = useRef<HTMLButtonElement | null>(null)

  const [duration, setDuration] = useState(0)
  const [time, setTime] = useState(0)
  const [playing, setPlaying] = useState(false)
  const [ready, setReady] = useState(false)
  const [failed, setFailed] = useState(false)
  const [natural, setNatural] = useState<{ w: number; h: number } | null>(null)
  const exactClock = HAS_RVFC
  const [imprecise, setImprecise] = useState(false)
  const [dragFrame, setDragFrame] = useState<number | null>(null)
  const [hoverFrame, setHoverFrame] = useState<number | null>(null)
  const [fullscreen, setFullscreen] = useState(false)
  const [inFrame, setInFrame] = useState<number | null>(null)
  const [outFrame, setOutFrame] = useState<number | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  const [busy, setBusy] = useState<null | 'clip' | 'frame'>(null)
  const [notice, setNotice] = useState<Notice | null>(null)

  const frames =
    framesProp ?? entry?.length ?? (duration > 0 ? frameCount(duration, effFps) : 0)
  const lastFrame = Math.max(0, frames - 1)
  const liveFrame = frameAt(time, effFps, frames)
  const currentFrame = dragFrame ?? liveFrame
  const hasRegion = inFrame !== null && outFrame !== null && outFrame > inFrame

  // Refs the long-lived callbacks read, so the frame clock and the key handler
  // never close over a stale render.
  const seekBusy = useRef(false)
  const seekPending = useRef<number | null>(null)
  const seekTimer = useRef(0)
  const wantFrame = useRef<number | null>(null)
  const drift = useRef(0)
  const railFocused = useRef(false)
  const fullscreenRef = useRef(false)
  const wasPlaying = useRef(false)
  const dragFrameRef = useRef<number | null>(null)
  const abortRef = useRef<AbortController | null>(null)
  const impreciseRef = useRef(false)
  const regionRef = useRef<{ in: number; out: number } | null>(null)
  const loopRef = useRef(loop)
  const checkRegionRef = useRef<(t: number) => void>(() => {})

  // Kept in refs so the frame clock and the window key handler always read the
  // current values without being torn down and rebuilt on every state change.
  useEffect(() => {
    impreciseRef.current = imprecise
    loopRef.current = loop
    regionRef.current = hasRegion && inFrame !== null && outFrame !== null
      ? { in: inFrame, out: outFrame }
      : null
    fullscreenRef.current = fullscreen
  })

  const say = useCallback(
    (kind: Notice['kind'], text: string) => {
      setNotice({ kind, text })
      onNotice?.(text)
    },
    [onNotice],
  )

  // --- seeking ------------------------------------------------------------
  // One seek in flight at a time. A pointer dragged across a 121-frame clip
  // would otherwise queue eighty seeks the decoder has to honour in order.

  const applySeek = useCallback((t: number) => {
    const v = videoRef.current
    if (!v) return
    const limit = Math.max(0, (Number.isFinite(v.duration) ? v.duration : 0) - 0.001)
    const target = clamp(t, 0, limit)
    if (Math.abs(v.currentTime - target) < 1e-4) {
      seekBusy.current = false
      return
    }
    seekBusy.current = true
    window.clearTimeout(seekTimer.current)
    // Some builds never fire `seeked` for a seek they coalesce away. Do not
    // let that wedge the rail.
    seekTimer.current = window.setTimeout(() => {
      seekBusy.current = false
    }, 1500)
    try {
      v.currentTime = target
    } catch {
      seekBusy.current = false
    }
  }, [])

  const seek = useCallback(
    (t: number) => {
      if (seekBusy.current) {
        seekPending.current = t
        return
      }
      applySeek(t)
    },
    [applySeek],
  )

  const goToFrame = useCallback(
    (f: number, opts: { pause?: boolean; track?: boolean } = {}) => {
      const v = videoRef.current
      if (!v || frames <= 0) return
      const target = clamp(Math.round(f), 0, lastFrame)
      if (opts.pause !== false) v.pause()
      wantFrame.current = opts.track === false ? null : target
      drift.current = 0
      seek(timeOfFrame(target, effFps))
    },
    [effFps, frames, lastFrame, seek],
  )

  const step = useCallback(
    (delta: number) => {
      const v = videoRef.current
      if (!v) return
      v.pause()
      if (impreciseRef.current) {
        // The decoder will not land where we ask it to, so walk from where we
        // actually are. Repeated steps still advance, one frame at a time.
        wantFrame.current = null
        seek(v.currentTime + delta / effFps)
        return
      }
      goToFrame(frameAt(v.currentTime, effFps, frames) + delta)
    },
    [effFps, frames, goToFrame, seek],
  )

  const skipSeconds = useCallback(
    (secs: number) => goToFrame(liveFrame + Math.round(secs * effFps)),
    [effFps, goToFrame, liveFrame],
  )

  const handleSeeked = useCallback(() => {
    const v = videoRef.current
    if (!v) return
    window.clearTimeout(seekTimer.current)
    seekBusy.current = false
    setTime(v.currentTime)

    const want = wantFrame.current
    if (want !== null && seekPending.current === null && fps !== null) {
      const landed = frameAt(v.currentTime, effFps, frames)
      if (landed !== want) {
        if (drift.current === 0) {
          drift.current = 1
          wantFrame.current = want
          applySeek(timeOfFrame(want, effFps) + (want - landed) / effFps)
          return
        }
        setImprecise(true)
      }
      wantFrame.current = null
      drift.current = 0
    }

    if (seekPending.current !== null) {
      const next = seekPending.current
      seekPending.current = null
      applySeek(next)
    }
  }, [applySeek, effFps, fps, frames])

  // --- the A–B region -----------------------------------------------------

  const checkRegion = useCallback(
    (t: number) => {
      const v = videoRef.current
      const region = regionRef.current
      if (!v || !region || v.paused) return
      const end = (region.out + 1) / effFps
      if (t >= end - 0.001) {
        if (loopRef.current) applySeek(timeOfFrame(region.in, effFps))
        else {
          v.pause()
          goToFrame(region.out)
        }
      }
    },
    [applySeek, effFps, goToFrame],
  )

  useEffect(() => {
    checkRegionRef.current = checkRegion
  }, [checkRegion])

  // --- the frame clock ----------------------------------------------------
  // requestVideoFrameCallback fires once per presented frame, including the
  // single frame a seek renders while paused, so it costs nothing at rest.

  useEffect(() => {
    const v = videoRef.current
    if (!v || !src || !HAS_RVFC) return

    let handle = 0
    let stopped = false
    const onFrame = (_now: number, meta: VideoFrameCallbackMetadata) => {
      if (stopped) return
      const t = meta.mediaTime
      setTime((prev) => (Math.abs(prev - t) > 0.0005 ? t : prev))
      checkRegionRef.current(t)
      handle = v.requestVideoFrameCallback(onFrame)
    }
    handle = v.requestVideoFrameCallback(onFrame)
    return () => {
      stopped = true
      try {
        v.cancelVideoFrameCallback(handle)
      } catch {
        /* the element is already gone */
      }
    }
  }, [src])

  // --- lifecycle ----------------------------------------------------------


  useEffect(() => {
    const v = videoRef.current
    if (v) v.playbackRate = speed
  }, [speed, ready])

  useEffect(() => {
    if (autoFocus) rootRef.current?.focus({ preventScroll: true })
  }, [autoFocus])

  useEffect(
    () => () => {
      window.clearTimeout(seekTimer.current)
      abortRef.current?.abort()
    },
    [],
  )

  useEffect(() => {
    if (!notice) return
    const t = window.setTimeout(() => setNotice(null), 6000)
    return () => window.clearTimeout(t)
  }, [notice])

  useEffect(() => {
    const onChange = () => setFullscreen(document.fullscreenElement === rootRef.current)
    document.addEventListener('fullscreenchange', onChange)
    return () => document.removeEventListener('fullscreenchange', onChange)
  }, [])

  useEffect(() => {
    if (!menuOpen) return
    const onDown = (e: PointerEvent) => {
      // A pointer that lands outside has already chosen where focus goes, so
      // this close does not drag it back to the trigger.
      if (!menuRef.current?.contains(e.target as Node)) setMenuOpen(false)
    }
    document.addEventListener('pointerdown', onDown)
    return () => document.removeEventListener('pointerdown', onDown)
  }, [menuOpen])

  /**
   * Opening the menu has to move focus into it.
   *
   * `u` opens it from anywhere in the player, and a controller or keyboard only
   * session is an ordinary session on this machine. Without this the menu
   * appeared, focus stayed wherever it was, and the two items could only be
   * reached by tabbing forward through the entire rest of the page.
   */
  useEffect(() => {
    if (!menuOpen) return
    menuPanel.current?.querySelector<HTMLElement>('[role="menuitem"]')?.focus()
  }, [menuOpen])

  /** Close and hand focus back to the word that opened it. */
  const closeMenu = useCallback(() => {
    setMenuOpen(false)
    menuTrigger.current?.focus()
  }, [])

  const onMenuKey = useCallback(
    (e: ReactKeyboardEvent<HTMLDivElement>) => {
      const items = [
        ...(menuPanel.current?.querySelectorAll<HTMLElement>('[role="menuitem"]') ?? []),
      ]
      if (!items.length) return
      const here = items.indexOf(document.activeElement as HTMLElement)
      const take = () => {
        e.preventDefault()
        e.stopPropagation()
      }
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        take()
        const step = e.key === 'ArrowDown' ? 1 : -1
        items[(Math.max(0, here) + step + items.length) % items.length].focus()
      } else if (e.key === 'Home' || e.key === 'End') {
        take()
        items[e.key === 'Home' ? 0 : items.length - 1].focus()
      } else if (e.key === 'Escape' || e.key === 'Tab') {
        // Tab closes rather than trapping: this is a menu hanging off a word in
        // a control row, not a dialog, and tabbing out of it is a reasonable
        // thing to want. It closes so nothing is left open behind the caret.
        take()
        closeMenu()
      }
    },
    [closeMenu],
  )

  // --- transport ----------------------------------------------------------

  const togglePlay = useCallback(() => {
    const v = videoRef.current
    if (!v || !ready) return
    if (v.paused) {
      const atEnd = Number.isFinite(v.duration) && v.currentTime >= v.duration - 1 / (effFps * 2)
      if (atEnd && !regionRef.current) applySeek(timeOfFrame(0, effFps))
      void v.play().catch(() => say('error', 'The browser would not start playback. Press play again.'))
    } else {
      v.pause()
    }
  }, [applySeek, effFps, ready, say])

  /** Clicking the frame also gives the shell focus, so Space works next. */
  const handleFrameClick = useCallback(() => {
    rootRef.current?.focus({ preventScroll: true })
    togglePlay()
  }, [togglePlay])

  const toggleLoop = useCallback(() => settings.patch({ loop: !settings.get().loop }), [])

  const setSpeed = useCallback((s: number) => settings.patch({ speed: s }), [])

  const cycleSpeed = useCallback(
    (dir: 1 | -1) => {
      const i = SPEEDS.indexOf(speed)
      setSpeed(SPEEDS[clamp((i < 0 ? 2 : i) + dir, 0, SPEEDS.length - 1)])
    },
    [setSpeed, speed],
  )

  const toggleFullscreen = useCallback(() => {
    const root = rootRef.current
    if (!root) return
    if (document.fullscreenElement === root) {
      void document.exitFullscreen().catch(() => {})
    } else {
      void root.requestFullscreen?.().catch(() =>
        say('error', 'This browser would not go full screen for us.'),
      )
    }
  }, [say])

  const markIn = useCallback(() => {
    setInFrame(currentFrame)
    setOutFrame((out) => (out !== null && out <= currentFrame ? null : out))
  }, [currentFrame])

  const markOut = useCallback(() => {
    setOutFrame(currentFrame)
    setInFrame((start) => (start !== null && start >= currentFrame ? null : start))
  }, [currentFrame])

  const clearRegion = useCallback(() => {
    setInFrame(null)
    setOutFrame(null)
  }, [])

  // --- saving -------------------------------------------------------------

  const clipName = useMemo(() => {
    const ext = clip ? extension(clip.filename) || '.webm' : '.webm'
    if (entry) return `switchgen-${entry.familyId}-${entry.seed}${ext}`
    return clip ? `${stem(clip.filename)}${ext}` : `switchgen-clip${ext}`
  }, [clip, entry])

  const frameNameFor = useCallback(
    (f: number) => {
      const base = entry
        ? `switchgen-${entry.familyId}-${entry.seed}`
        : clip
          ? stem(clip.filename)
          : 'switchgen-frame'
      return `${base}-f${padFrame(f, Math.max(frames, 1))}.png`
    },
    [clip, entry, frames],
  )

  const saveClip = useCallback(async () => {
    if (!src || busy) return
    setBusy('clip')
    const ac = new AbortController()
    abortRef.current = ac
    try {
      const res = await fetch(src, { signal: ac.signal })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      saveBlob(await res.blob(), clipName)
      say('info', `Saved as ${clipName}`)
    } catch (err) {
      if ((err as Error | null)?.name !== 'AbortError') {
        say('error', 'We could not save the clip. The server did not hand the file over. Try again.')
      }
    } finally {
      abortRef.current = null
      setBusy(null)
    }
  }, [busy, clipName, say, src])

  /** The displayed frame as a PNG. Null when the browser will not release it. */
  const grabFrame = useCallback(async (): Promise<Blob | null> => {
    const v = videoRef.current
    if (!v || !v.videoWidth || !v.videoHeight) return null
    try {
      const canvas = document.createElement('canvas')
      canvas.width = v.videoWidth
      canvas.height = v.videoHeight
      const ctx = canvas.getContext('2d')
      if (!ctx) return null
      ctx.drawImage(v, 0, 0, canvas.width, canvas.height)
      return await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'))
    } catch {
      return null
    }
  }, [])

  const saveFrame = useCallback(async () => {
    if (busy || !ready) return
    videoRef.current?.pause()
    setBusy('frame')
    const blob = await grabFrame()
    setBusy(null)
    if (!blob) {
      say('error', 'We could not copy that frame out of the clip. Save the whole clip instead.')
      return
    }
    const name = frameNameFor(currentFrame)
    saveBlob(blob, name)
    say('info', `Saved as ${name}`)
  }, [busy, currentFrame, frameNameFor, grabFrame, ready, say])

  const canUseFrame = !!onUseFrame || !!entry

  const sendFrameTo = useCallback(
    async (desk: DeskId) => {
      setMenuOpen(false)
      if (!canUseFrame) return
      videoRef.current?.pause()
      const f = currentFrame
      const where = desk === 'images' ? 'the pictures desk' : 'the video desk as a start frame'

      if (onUseFrame) {
        setBusy('frame')
        const blob = await grabFrame()
        setBusy(null)
        if (!blob) {
          say('error', 'We could not copy that frame out of the clip.')
          return
        }
        const name = frameNameFor(f)
        onUseFrame({
          desk,
          frame: f,
          time: timeOfFrame(f, effFps),
          blob,
          file: new File([blob], name, { type: 'image/png' }),
          entry,
          clip,
        })
        say('info', `Frame ${padFrame(f, Math.max(frames, 1))} sent to ${where}.`)
        return
      }

      if (entry) {
        adoptSource(entry, desk, { frame: f })
        say('info', `Frame ${padFrame(f, Math.max(frames, 1))} sent to ${where}.`)
      }
    },
    [canUseFrame, clip, currentFrame, effFps, entry, frameNameFor, frames, grabFrame, onUseFrame, say],
  )

  // --- keyboard -----------------------------------------------------------

  useEffect(() => {
    if (keyboard === 'off' || !src) return
    const onKey = (e: KeyboardEvent) => {
      if (e.defaultPrevented) return
      if (isTypingTarget(e.target)) return
      if (e.ctrlKey || e.metaKey || e.altKey) return
      const root = rootRef.current
      const inside = !!root && !!document.activeElement && root.contains(document.activeElement)
      if (keyboard === 'scoped' && !inside && !fullscreenRef.current) return

      const take = () => e.preventDefault()
      const key = e.key
      const lower = key.length === 1 ? key.toLowerCase() : key

      switch (lower) {
        case ' ':
        case 'k':
          take()
          return togglePlay()
        case ',':
        case '<':
          take()
          return step(-1)
        case '.':
        case '>':
          take()
          return step(1)
        case 'ArrowLeft':
          if (railFocused.current) return
          take()
          return e.shiftKey ? skipSeconds(-1) : step(-1)
        case 'ArrowRight':
          if (railFocused.current) return
          take()
          return e.shiftKey ? skipSeconds(1) : step(1)
        case 'Home':
          if (railFocused.current) return
          take()
          return goToFrame(0)
        case 'End':
          if (railFocused.current) return
          take()
          return goToFrame(lastFrame)
        case '[':
          take()
          return cycleSpeed(-1)
        case ']':
          take()
          return cycleSpeed(1)
        case 'l':
        case 'r':
          take()
          return toggleLoop()
        case 'i':
          take()
          return e.shiftKey ? clearRegion() : markIn()
        case 'o':
          take()
          return markOut()
        case 'f':
          take()
          return toggleFullscreen()
        case 's':
          take()
          void saveClip()
          return
        case 'g':
          take()
          void saveFrame()
          return
        case 'u':
          if (!canUseFrame) return
          take()
          if (menuOpen) return closeMenu()
          return setMenuOpen(true)
        case 'Escape':
          if (menuOpen) {
            take()
            return closeMenu()
          }
          if (document.fullscreenElement === rootRef.current) {
            take()
            void document.exitFullscreen().catch(() => {})
          }
          return
        default:
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [
    canUseFrame,
    clearRegion,
    closeMenu,
    cycleSpeed,
    goToFrame,
    keyboard,
    lastFrame,
    markIn,
    markOut,
    menuOpen,
    saveClip,
    saveFrame,
    skipSeconds,
    src,
    step,
    toggleFullscreen,
    toggleLoop,
    togglePlay,
  ])

  // --- video element handlers --------------------------------------------

  const handleLoadedMetadata = useCallback(() => {
    const v = videoRef.current
    if (!v) return
    setDuration(Number.isFinite(v.duration) ? v.duration : 0)
    setNatural(v.videoWidth ? { w: v.videoWidth, h: v.videoHeight } : null)
    setReady(true)
    v.playbackRate = speed
    // Show the first frame rather than a black rectangle. This is a seek, not
    // playback: nothing starts on its own, ever.
    if (v.currentTime < 1e-4) applySeek(timeOfFrame(0, effFps))
  }, [applySeek, effFps, speed])

  const handleTimeUpdate = useCallback(() => {
    const v = videoRef.current
    if (!v) return
    if (!exactClock) setTime(v.currentTime)
    checkRegionRef.current(v.currentTime)
  }, [exactClock])

  const handleEnded = useCallback(() => {
    const v = videoRef.current
    if (!v) return
    if (loopRef.current) {
      const region = regionRef.current
      applySeek(timeOfFrame(region ? region.in : 0, effFps))
      void v.play().catch(() => setPlaying(false))
    } else {
      setPlaying(false)
    }
  }, [applySeek, effFps])

  // --- scrubbing ----------------------------------------------------------

  const onScrubStart = useCallback(() => {
    const v = videoRef.current
    wasPlaying.current = !!v && !v.paused
    v?.pause()
  }, [])

  const onScrub = useCallback(
    (f: number) => {
      // Paint the playhead where the pointer is straight away; the decoder
      // catches up behind us. A slow seek never makes the rail feel stuck.
      dragFrameRef.current = f
      setDragFrame(f)
      wantFrame.current = null
      seek(timeOfFrame(f, effFps))
    },
    [effFps, seek],
  )

  const onScrubEnd = useCallback(() => {
    const f = dragFrameRef.current
    dragFrameRef.current = null
    setDragFrame(null)
    if (f !== null) goToFrame(f, { pause: false })
    if (wasPlaying.current) void videoRef.current?.play().catch(() => {})
    wasPlaying.current = false
  }, [goToFrame])

  // --- captions -----------------------------------------------------------

  const size = natural
    ? dimensions(natural.w, natural.h)
    : dimensions(entry?.width ?? null, entry?.height ?? null)

  const spec = useMemo(() => {
    const parts: string[] = []
    if (clip) parts.push(clip.filename)
    if (size) parts.push(size)
    if (frames > 0) parts.push(fps ? `${frames} frames at ${fps} fps` : `${frames} frames`)
    parts.push('silent', 'no audio track')
    return parts.join(' · ')
  }, [clip, fps, frames, size])

  const generatedByline = entry
    ? [
        `Made by ${entry.modelLabel || entry.familyLabel}`,
        britishDateTime(entry.at),
        humanDuration(entry.durationMs),
      ]
        .filter(Boolean)
        .join(' · ')
    : null

  const footnote = !exactClock
    ? '† Frame numbers are approximate in this browser.'
    : imprecise
      ? '† This clip seeks to the nearest available frame, so a step may land one frame out.'
      : fps === null
        ? '† No frame rate was recorded for this clip, so it is timed rather than counted.'
        : null

  const aspect = natural
    ? `${natural.w} / ${natural.h}`
    : entry?.width && entry?.height
      ? `${entry.width} / ${entry.height}`
      : undefined

  const speedLabel = SPEED_LABEL[String(speed)] ?? `${speed}×`
  const disabled = !src || !ready || failed

  // --- render -------------------------------------------------------------

  return (
    <section
      ref={rootRef}
      tabIndex={-1}
      aria-label={entry ? `Clip viewer, No. ${entry.no}` : 'Clip viewer'}
      className={`flex w-full flex-col bg-newsprint ${RING} ${
        fullscreen ? 'h-[calc(100dvh-var(--sg-safe-t)-var(--sg-safe-b))] justify-center p-6' : ''
      } ${className}`}
    >
      {/* the frame */}
      <div
        className={`relative flex items-center justify-center overflow-hidden border border-grey-300 bg-newsprint-aged ${
          fullscreen ? 'min-h-0 flex-1' : ''
        }`}
        style={!fullscreen && aspect ? { aspectRatio: aspect } : undefined}
      >
        {!src ? (
          <p className="px-8 py-16 text-center text-small italic text-grey-500">
            Nothing to play yet. Make a clip on the video desk and it will open here.
          </p>
        ) : failed ? (
          <div className="max-w-md px-8 py-12">
            <p className="text-overline font-semibold uppercase tracking-[0.18em] text-grey-700">
              We could not open this clip
            </p>
            <p className="mt-2 text-small text-ink">
              The file has been moved or deleted, or this browser cannot play it. The settings that
              made it are still in the archive, so you can make it again.
            </p>
          </div>
        ) : (
          <>
            <video
              ref={videoRef}
              src={src}
              poster={poster ?? undefined}
              preload="metadata"
              playsInline
              muted
              loop={loop && !hasRegion}
              className="max-h-full max-w-full cursor-pointer object-contain"
              onClick={handleFrameClick}
              onDoubleClick={toggleFullscreen}
              onLoadedMetadata={handleLoadedMetadata}
              onDurationChange={handleLoadedMetadata}
              onSeeked={handleSeeked}
              onPlay={() => setPlaying(true)}
              onPause={() => setPlaying(false)}
              onEnded={handleEnded}
              onTimeUpdate={handleTimeUpdate}
              onError={() => setFailed(true)}
            />
            {!ready && (
              <p className="pointer-events-none absolute text-small italic text-grey-500">
                Opening the clip…
              </p>
            )}
          </>
        )}
      </div>

      <Hairline />

      {/* the rail and its ruler */}
      <div className="pt-2">
        <ScrubRail
          value={currentFrame}
          max={lastFrame}
          fps={effFps}
          showFrames={fps !== null}
          disabled={disabled || frames <= 1}
          inFrame={inFrame}
          outFrame={outFrame}
          onSeek={onScrub}
          onScrubStart={onScrubStart}
          onScrubEnd={onScrubEnd}
          onHover={setHoverFrame}
          onFocusChange={(focused) => {
            railFocused.current = focused
          }}
        />
        <FrameTicks count={frames > 1 ? frames : 0} />
      </div>

      {/* the transport */}
      <div className="flex min-h-8 flex-wrap items-center gap-y-1 py-1">
        <IconButton
          glyph={playing ? 'pause' : 'play'}
          label={playing ? 'Pause' : 'Play'}
          hint="Space"
          pressed={playing}
          disabled={disabled}
          onClick={togglePlay}
        />
        <IconButton
          glyph="first"
          label="First frame"
          hint="Home"
          disabled={disabled}
          onClick={() => goToFrame(0)}
        />
        <IconButton
          glyph="prev"
          label="Back one frame"
          hint="comma"
          disabled={disabled}
          onClick={() => step(-1)}
        />
        <IconButton
          glyph="next"
          label="Forward one frame"
          hint="full stop"
          disabled={disabled}
          onClick={() => step(1)}
        />
        <IconButton
          glyph="last"
          label="Last frame"
          hint="End"
          disabled={disabled}
          onClick={() => goToFrame(lastFrame)}
        />

        <Divider />

        <Readout
          frame={currentFrame}
          frames={frames}
          time={dragFrame !== null ? timeOfFrame(dragFrame, effFps) : time}
          duration={duration}
          fps={fps}
          exact={exactClock && !imprecise}
        />

        <Divider />

        <TextButton onClick={toggleLoop} active={loop} toggle label="Loop" hint="L">
          Loop
        </TextButton>

        <span className="text-overline font-semibold uppercase tracking-[0.16em] text-grey-500">
          A–B
        </span>
        <TextButton onClick={markIn} label="Set the loop start" hint="I" disabled={disabled}>
          In
        </TextButton>
        <TextButton onClick={markOut} label="Set the loop end" hint="O" disabled={disabled}>
          Out
        </TextButton>
        {hasRegion && (
          <>
            <span className="px-1 text-caption tabular-nums text-grey-700">
              {clock(inFrame / effFps)} → {clock((outFrame + 1) / effFps)}
            </span>
            <TextButton onClick={clearRegion} label="Clear the loop range" hint="Shift + I">
              Clear
            </TextButton>
          </>
        )}

        <Divider />

        <span className="inline-flex border border-grey-300 divide-x divide-grey-300">
          {SPEEDS.map((s) => (
            <TextButton
              key={s}
              onClick={() => setSpeed(s)}
              active={speed === s}
              label={`Play at ${SPEED_LABEL[String(s)] ?? `${s}×`}`}
              hint="[ and ]"
            >
              {SPEED_LABEL[String(s)] ?? `${s}×`}
            </TextButton>
          ))}
        </span>

        <Divider />

        <IconButton
          glyph={fullscreen ? 'exit-fullscreen' : 'fullscreen'}
          label={fullscreen ? 'Leave full screen' : 'Full screen'}
          hint="F"
          disabled={!src}
          onClick={toggleFullscreen}
        />

        {/* the editorial actions sit at the far end of the row */}
        <span className="flex w-full flex-wrap items-center gap-x-4 gap-y-1 pt-1 sm:ml-auto sm:w-auto sm:flex-nowrap sm:pt-0 sm:pl-4">
          <LinkAction onClick={() => void saveClip()} disabled={!src || busy === 'clip'} hint="S">
            {busy === 'clip' ? 'Saving…' : 'Save the clip'}
          </LinkAction>
          <LinkAction onClick={() => void saveFrame()} disabled={disabled || busy === 'frame'} hint="G">
            Save this frame
          </LinkAction>
          {canUseFrame && (
            <span className="relative" ref={menuRef}>
              <LinkAction
                buttonRef={menuTrigger}
                onClick={() => (menuOpen ? closeMenu() : setMenuOpen(true))}
                disabled={disabled}
                hint="U"
                expanded={menuOpen}
              >
                Use this frame →
              </LinkAction>
              {menuOpen && (
                <div
                  ref={menuPanel}
                  role="menu"
                  aria-label="Use this frame"
                  onKeyDown={onMenuKey}
                  className="absolute right-0 bottom-full z-20 mb-1 w-64 border border-grey-300 bg-newsprint"
                >
                  <button
                    type="button"
                    role="menuitem"
                    onClick={() => void sendFrameTo('images')}
                    className={`block w-full px-3 py-2 text-left text-small text-ink hover:bg-newsprint-aged ${RING}`}
                  >
                    <span className="block">Pictures</span>
                    <span className="block text-caption text-grey-700">Work from it</span>
                  </button>
                  <div className="h-px w-full bg-grey-300" />
                  <button
                    type="button"
                    role="menuitem"
                    onClick={() => void sendFrameTo('video')}
                    className={`block w-full px-3 py-2 text-left text-small text-ink hover:bg-newsprint-aged ${RING}`}
                  >
                    <span className="block">Video</span>
                    <span className="block text-caption text-grey-700">As a start frame</span>
                  </button>
                </div>
              )}
            </span>
          )}
        </span>
      </div>

      <Hairline />

      {/* the caption block */}
      <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-1 pt-2">
        <p className="text-caption text-grey-700">{caption ?? spec}</p>
        <p className="text-caption tabular-nums text-grey-500" aria-live="off">
          {hoverFrame !== null && fps !== null
            ? `frame ${padFrame(hoverFrame, Math.max(frames, 1))} · ${clock(hoverFrame / effFps)}`
            : hoverFrame !== null
              ? clock(hoverFrame / effFps)
              : speedLabel !== '1×'
                ? `playing at ${speedLabel}`
                : ''}
        </p>
      </div>

      {(byline ?? generatedByline) && (
        <p className="pt-1 text-caption text-grey-700">{byline ?? generatedByline}</p>
      )}

      {footnote && <p className="pt-1 text-caption italic text-grey-500">{footnote}</p>}

      {notice && (
        <p
          role="status"
          className={`mt-2 border-l-2 pl-3 text-caption ${
            notice.kind === 'error' ? 'border-error text-error' : 'border-grey-300 text-grey-700'
          }`}
        >
          {notice.text}
        </p>
      )}
    </section>
  )
}

export default Player
